### ISSUE TITLE
don't work on windows

### ISSUE THREAD

**Issue by tsvetkovpro** [waigo/waigo.github.io#2]
i mean: waigo.github.io-source

good day, i clone repo, npm i -D , and then gatsby develop.
but its not workink for me on windows 10 x64. i got this error:

can you help me please?

![image](https://cloud.githubusercontent.com/assets/2004857/21376138/74a623d6-c754-11e6-91cd-b98ff9e0abc4.png)

**Comment by hiddentao** [comment]
Do other gatsby projects work for you?

**Comment by tsvetkovpro** [comment]
yes, my site on gatsby work fine in same env: https://github.com/tsvetkovpro/tsvetkovpro.github.io

**Comment by hiddentao** [comment]
It's probably an error in the custom JS code running in the site. What browser are you testing on?

**Comment by tsvetkovpro** [comment]
Chrome  54.0.2840.99 m (64-bit)

![image](https://cloud.githubusercontent.com/assets/2004857/21584620/fc8ac5f2-d0cf-11e6-92ed-60f7ad8673c6.png)

**Comment by tsvetkovpro** [comment]
error in my console: 

![image](https://cloud.githubusercontent.com/assets/2004857/21584630/662bbc0a-d0d0-11e6-9132-e22b2db1a7c8.png)

**Comment by tsvetkovpro** [comment]
i think missing file and folder ../data/apiNav.json

**Comment by hiddentao** [comment]
Ah you have to run `npm run setup` first. My fault for not adding that to the README

**Comment by tsvetkovpro** [comment]
thanks a lot!!! works fine for me. 

p.s. on my windows i use this command: `node ./scripts/setup.js` . `npm run setup` dont work.
